### ISSUE TITLE
Will this native session support for CI3?

### ISSUE THREAD

**Issue by harrykc** [appleboy/CodeIgniter-Native-Session#12]
The session library rewrite in CI3, will it support CI3?
Refer to custom driver
http://www.codeigniter.com/user_guide/libraries/sessions.html#custom-drivers

some functions such as sess_regenerate missing in this repository.
Thanks

**Comment by appleboy** [comment]
@harrykc CI3 has been supported session library so you don't need this library now.

**Comment by bsenyuva** [comment]
Question, what is proper way to use native PHP session in CI3?

**Comment by appleboy** [comment]
See: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/Session.php

and https://www.codeigniter.com/user_guide/libraries/sessions.html

**Comment by bsenyuva** [comment]
I know those but I want to use PHP's own session infrastructure instead of CI3 session mechanism. I couldn't find a configuration to do that except your library. CI's session mostly unreliable in my opinion, especially when ajax comes in. Also I want to use Redis cluster instead of on Redis server.
